name: 🐛 Bugfix
description: Fix a bug
title: "[Bugfix] "
labels: ["bugfix"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is the issue?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Proposed Fix
      description: How should this be fixed?
    validations:
      required: false
