name: 🔧 Chore
description: Config, refactoring, or maintenance work
title: "[Chore] "
labels: ["chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ]
        - [ ]
    validations:
      required: false
