name: ✨ Feature
description: New user-facing feature
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature are you proposing?
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ]
        - [ ]
    validations:
      required: false
