name: Task
description: General task
title: "[Task] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: "## Task"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Break down the work
      value: |
        - [ ] 
        - [ ] 
    validations:
      required: false